version: '3'

services:

  init:
    build: .
    image: netflixoss/aardvark:latest
    volumes:
      - data:/data
    depends_on:
      - pg
    links:
      - pg
    env_file: .env
    command: [ "aardvark", "create_db" ]

  api:
    build: .
    image: netflixoss/aardvark:latest
    depends_on:
      - init
      - pg
    links:
      - pg
    ports:
      - 5000:5000
    volumes:
      - data:/data
    env_file: .env
    command: [ "aardvark", "start_api", "-b", "0.0.0.0:5000" ]

  collector:
    build: .
    image: netflixoss/aardvark:latest
    depends_on:
      - init
      - pg
    links:
      - pg
    restart: always
    volumes:
      - data:/data
    env_file: .env
    command: [ "aardvark", "update", "-a", "$AARDVARK_ACCOUNTS" ]

  pg:
    image: postgres:11
    restart: unless-stopped
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: aardvark
      POSTGRES_PASSWORD: aardvark
      POSTGRES_DB: postgres
    ports:
      - 5432:5432

volumes:
  data:
